//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoHiemXaHoi
    {
        public int idBaoHiemXaHoi { get; set; }
        public int idVienChuc { get; set; }
        public string soSo { get; set; }
        public Nullable<System.DateTime> ngayThamGia { get; set; }
        public Nullable<System.DateTime> ngayCapSo { get; set; }
        public Nullable<System.DateTime> ngayRutSo { get; set; }
        public string ghiChu { get; set; }
    
        public virtual VienChuc VienChuc { get; set; }
    }
}
