//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucVuDonViVienChuc
    {
        public int idChucVuDonViVienChuc { get; set; }
        public int idVienChuc { get; set; }
        public Nullable<int> idChucVu { get; set; }
        public Nullable<int> idDonVi { get; set; }
        public Nullable<int> idToChuyenMon { get; set; }
        public string phanLoaiCongTac { get; set; }
        public Nullable<int> checkPhanLoaiCongTac { get; set; }
        public Nullable<System.DateTime> ngayBatDau { get; set; }
        public Nullable<System.DateTime> ngayKetThuc { get; set; }
        public Nullable<int> loaiThayDoi { get; set; }
        public Nullable<int> kiemNhiem { get; set; }
        public string linkVanBanDinhKem { get; set; }
        public string ghiChu { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        public virtual DonVi DonVi { get; set; }
        public virtual ToChuyenMon ToChuyenMon { get; set; }
        public virtual VienChuc VienChuc { get; set; }

        public ChucVuDonViVienChuc(ChucVuDonViVienChuc chucVuDonViVienChuc)
        {
            idChucVuDonViVienChuc = chucVuDonViVienChuc.idChucVuDonViVienChuc;
            idVienChuc = chucVuDonViVienChuc.idVienChuc;
            idChucVu = chucVuDonViVienChuc.idDonVi;
            idToChuyenMon = chucVuDonViVienChuc.idToChuyenMon;
            phanLoaiCongTac = chucVuDonViVienChuc.phanLoaiCongTac;
            checkPhanLoaiCongTac = chucVuDonViVienChuc.checkPhanLoaiCongTac;
            ngayBatDau = chucVuDonViVienChuc.ngayBatDau;
            ngayKetThuc = chucVuDonViVienChuc.ngayKetThuc;
            linkVanBanDinhKem = chucVuDonViVienChuc.linkVanBanDinhKem;
            loaiThayDoi = chucVuDonViVienChuc.loaiThayDoi;
            kiemNhiem = chucVuDonViVienChuc.kiemNhiem;
            ChucVu = chucVuDonViVienChuc.ChucVu;
            DonVi = chucVuDonViVienChuc.DonVi;
            ToChuyenMon = chucVuDonViVienChuc.ToChuyenMon;
            VienChuc = chucVuDonViVienChuc.VienChuc;
        }
        public ChucVuDonViVienChuc() { }
    }
}
