//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChucVu()
        {
            this.ChucVuDonViVienChucs = new HashSet<ChucVuDonViVienChuc>();
        }
    
        public int idChucVu { get; set; }
        public string tenChucVu { get; set; }
        public Nullable<double> heSoChucVu { get; set; }
        public int idLoaiChucVu { get; set; }
    
        public virtual LoaiChucVu LoaiChucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChucVuDonViVienChuc> ChucVuDonViVienChucs { get; set; }
    }
}
