//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonVi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonVi()
        {
            this.ChucVuDonViVienChucs = new HashSet<ChucVuDonViVienChuc>();
            this.ToChuyenMons = new HashSet<ToChuyenMon>();
        }
    
        public int idDonVi { get; set; }
        public string tenDonVi { get; set; }
        public string diaDiem { get; set; }
        public string diaChi { get; set; }
        public string sDT { get; set; }
        public int idLoaiDonVi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChucVuDonViVienChuc> ChucVuDonViVienChucs { get; set; }
        public virtual LoaiDonVi LoaiDonVi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToChuyenMon> ToChuyenMons { get; set; }
    }
}
