//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ngach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ngach()
        {
            this.Bacs = new HashSet<Bac>();
        }
    
        public int idNgach { get; set; }
        public string maNgach { get; set; }
        public string tenNgach { get; set; }
        public Nullable<int> heSoVuotKhungBaNamDau { get; set; }
        public Nullable<int> heSoVuotKhungTrenBaNam { get; set; }
        public Nullable<int> thoiHanNangBac { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bac> Bacs { get; set; }
    }
}
