//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bac()
        {
            this.QuaTrinhLuongs = new HashSet<QuaTrinhLuong>();
        }
    
        public int idBac { get; set; }
        public Nullable<int> bac1 { get; set; }
        public double heSoBac { get; set; }
        public int idNgach { get; set; }
    
        public virtual Ngach Ngach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuaTrinhLuong> QuaTrinhLuongs { get; set; }
    }
}
