//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocHamHocViVienChuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HocHamHocViVienChuc()
        {
            this.NganhVienChucs = new HashSet<NganhVienChuc>();
        }
    
        public int idHocHamHocViVienChuc { get; set; }
        public int idVienChuc { get; set; }
        public int idLoaiHocHamHocVi { get; set; }
        public int idLoaiNganh { get; set; }
        public int idNganhDaoTao { get; set; }
        public int idChuyenNganh { get; set; }
        public Nullable<int> bacHocHamHocVi { get; set; }
        public string tenHocHamHocVi { get; set; }
        public string coSoDaoTao { get; set; }
        public string nuocCapBang { get; set; }
        public string ngonNguDaoTao { get; set; }
        public string hinhThucDaoTao { get; set; }
        public Nullable<System.DateTime> ngayCapBang { get; set; }
        public string linkVanBanDinhKem { get; set; }
    
        public virtual ChuyenNganh ChuyenNganh { get; set; }
        public virtual LoaiHocHamHocVi LoaiHocHamHocVi { get; set; }
        public virtual LoaiNganh LoaiNganh { get; set; }
        public virtual NganhDaoTao NganhDaoTao { get; set; }
        public virtual VienChuc VienChuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NganhVienChuc> NganhVienChucs { get; set; }
    }
}
