//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiHocHamHocVi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiHocHamHocVi()
        {
            this.DangHocNangCaos = new HashSet<DangHocNangCao>();
            this.HocHamHocViVienChucs = new HashSet<HocHamHocViVienChuc>();
        }
    
        public int idLoaiHocHamHocVi { get; set; }
        public string tenLoaiHocHamHocVi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DangHocNangCao> DangHocNangCaos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HocHamHocViVienChuc> HocHamHocViVienChucs { get; set; }
    }
}
