//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanTriVien
    {
        public int id { get; set; }
        public string taikhoan { get; set; }
        public string matkhau { get; set; }
        public Nullable<int> phanQuyen { get; set; }
    }
}
