//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToChuyenMon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToChuyenMon()
        {
            this.ChucVuDonViVienChucs = new HashSet<ChucVuDonViVienChuc>();
        }
    
        public int idToChuyenMon { get; set; }
        public string tenToChuyenMon { get; set; }
        public int idDonVi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChucVuDonViVienChuc> ChucVuDonViVienChucs { get; set; }
        public virtual DonVi DonVi { get; set; }
    }
}
